name: Continuous integration

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz
#on:
#  merge_group:
#  pull_request:
#    branches:
#      - main
#      - feature/**
#      - release/**
#  push:
#    branches:
#      - main
#      - release/**

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: "./global.json"
    - name: Restore packages
      run: dotnet restore
    - name: Code format check
      run: dotnet format --no-restore --verify-no-changes
    - name: Build solution
      run: dotnet build --no-restore --configuration Release
    - uses: ./.github/actions/releaseNotes
