name: Create draft release

on:
  workflow_dispatch:

defaults:
  run:
    shell: powershell

jobs:
  create_release:
    name: Create release
    #runs-on: ubuntu-latest
    runs-on: windows-2022
    permissions: write-all
    outputs:
      releaseId: ${{ steps.new_release.outputs.id }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.TESTACTION_PAT }}

      
      # - name: Version bump
      #   id: new_version
      #   run: |
      #       ./src/buildscripts/github/setcurrentgithubdraftrelease.ps1 -GithubToken '${{ secrets.GITHUB_TOKEN }}'

      - name: Add Release notes File
        run: |
            New-Item -ItemType Directory -Path "src/buildscripts/artifacts" -Force -ErrorAction SilentlyContinue
            $releaseNotes = ./src/buildscripts/github/GetReleaseNotes.ps1 | Set-Content -Path "src/buildscripts/artifacts/ReleaseNotes.txt" -Force

      # - name: Release notes
      #   uses: ./.github/actions/releaseNotes

      # - name: Create Jira release
      #   run: src/buildscripts/github/SetJiraRelease.ps1 -Username '${{ secrets.JIRA_USERNAME }}' -Password '${{ secrets.JIRA_PASSWORD }}' -DefaultPackage 'TESTACTION.SAAS' -Version '${{ steps.new_version.outputs.version }}' -PreVersion '${{ steps.version_bump.outputs.sha_short }}'

      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Create and push new branch
        run: |
          # Define the new branch name (you can customize this)
          $NEW_BRANCH_NAME="release/v1.0.0"
          
          # Create a new branch
          git checkout -b $NEW_BRANCH_NAME

          # Push the new branch to the repository
          git push origin $NEW_BRANCH_NAME

          echo "New branch created: $NEW_BRANCH_NAME"

      - name: Create Github Release
        id: new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.1
          release_name: "release/v1.0.0"
          commitish: ${{ github.ref_name }}
          body_path: src/buildscripts/artifacts/ReleaseNotes.txt
          draft: true
          prerelease: false